name: meal_monkey
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"


dependencies:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  #Bottom Navigation
  curved_navigation_bar: ^1.0.3

  flutter:
    sdk: flutter
  
  #For Navigation
  flutter_hooks: ^0.18.3
  flutter_svg: ^1.0.3
  go_router: ^3.0.7
  hooks_riverpod: ^1.0.3
  logger: ^1.1.0
  

 

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  lint: ^1.8.2


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icons/


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Bold.ttf
          style: italic
    - family: Metropolis-Italic
      fonts:
        - asset: assets/fonts/Metropolis-Regular.ttf
        - asset: assets/fonts/Metropolis-BoldItalic.ttf
